# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Bakusai < Formula
  desc "cli for bakusai.com"
  homepage ""
  version "0.1.12"

  on_macos do
    on_intel do
      url "https://github.com/bonnou-shounen/bakusai/releases/download/v0.1.12/bakusai_0.1.12_darwin_amd64.zip"
      sha256 "ced1bfedfe1abf11efed077cf912d6494927e9e3ec2dbf0e6c19f84d1c7694de"

      def install
        bin.install "bakusai"
      end
    end
    on_arm do
      url "https://github.com/bonnou-shounen/bakusai/releases/download/v0.1.12/bakusai_0.1.12_darwin_arm64.zip"
      sha256 "9ca7c8012bb73a7cf7a8f0fbde177fbf3be180e0f89918b2a0b312791c81df9c"

      def install
        bin.install "bakusai"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/bonnou-shounen/bakusai/releases/download/v0.1.12/bakusai_0.1.12_linux_amd64.zip"
        sha256 "2152dd8ce09b3888a705ab92bcf63e54c6c118a8003b2e6a8af3e08c750e1797"

        def install
          bin.install "bakusai"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/bonnou-shounen/bakusai/releases/download/v0.1.12/bakusai_0.1.12_linux_arm64.zip"
        sha256 "fa939e97ed141b76e1ff02c882008a9ce711ae060b4209e1b6bb0bbe8a2dae03"

        def install
          bin.install "bakusai"
        end
      end
    end
  end
end
