# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Bakusai < Formula
  desc "cli for bakusai.com"
  homepage ""
  version "0.1.4"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/bonnou-shounen/bakusai/releases/download/v0.1.4/bakusai_0.1.4_darwin_amd64.zip"
      sha256 "335ef49551dd3ae30ee252101c8da17ea741685eb8c1457857f03eea0e09014c"

      def install
        bin.install "bakusai"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/bonnou-shounen/bakusai/releases/download/v0.1.4/bakusai_0.1.4_darwin_arm64.zip"
      sha256 "d40fdb6694cfab2b0e19aa90809367bd19c7b1a488fe0c48a58d2f48e0053606"

      def install
        bin.install "bakusai"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/bonnou-shounen/bakusai/releases/download/v0.1.4/bakusai_0.1.4_linux_amd64.zip"
      sha256 "13824c443e8bc229ecab7614e85ebe6a07f353a58bce3329d541aac3038f7b4c"

      def install
        bin.install "bakusai"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/bonnou-shounen/bakusai/releases/download/v0.1.4/bakusai_0.1.4_linux_arm64.zip"
      sha256 "181d08366ec6bbd1a65303f53b4841a3c3739f1d9dea72f4e54771d66e068694"

      def install
        bin.install "bakusai"
      end
    end
  end
end
