# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Bakusai < Formula
  desc "cli for bakusai.com"
  homepage ""
  version "0.1.8"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/bonnou-shounen/bakusai/releases/download/v0.1.8/bakusai_0.1.8_darwin_arm64.zip"
      sha256 "f76b8a2e55c1a6f47105232b7842780e90f6c382bfa9745c7454f790f7767758"

      def install
        bin.install "bakusai"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/bonnou-shounen/bakusai/releases/download/v0.1.8/bakusai_0.1.8_darwin_amd64.zip"
      sha256 "4a140a4fd7e3dfd984d5a3988d35ff18d1b2bd29164f3d42fade18acb9ee64a0"

      def install
        bin.install "bakusai"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/bonnou-shounen/bakusai/releases/download/v0.1.8/bakusai_0.1.8_linux_arm64.zip"
      sha256 "4315acefa07f3f8bdaa1c548047694d88702d957378c0e7c0e59d14e71243493"

      def install
        bin.install "bakusai"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/bonnou-shounen/bakusai/releases/download/v0.1.8/bakusai_0.1.8_linux_amd64.zip"
      sha256 "62df13518c02e07711e8f205575cc87e33ea579a04868e00868dfff324aa7e3b"

      def install
        bin.install "bakusai"
      end
    end
  end
end
